### ISSUE TITLE
The camera parameter of the undistorted images

### ISSUE THREAD

**Issue by liruihao** [oxford-ori/robotcar-dataset-sdk#8]
Hi,

Thank you very much for sharing and publishing the dataset.

I have one problem. I want to use the stereo images, but notice that only the original camera parameter and distortion bin file are provided. I tried to undistort the images using your SDK. But how could I get the new camera parameter? Do you have the undistorted camera parameter file?

Thank you very much for your help

Kind Regards,

Ruihao

**Comment by wmaddern** [comment]
Dear Ruihao,

The camera parameters provided are for the undistorted images in the form of [fx, fy, cx, cy] - we do not have the parameters for the distorted (raw) images since the calibration was performed at the factory at Point Grey. Please apply the undistortion using our SDK before using the images with the provided intrinsics.

For the Grasshopper2 images we provide recordings of checkerboards for calibration here:

http://robotcar-dataset.robots.ox.ac.uk/downloads/

Best,

Will.

**Comment by jimaldon** [comment]
@wmaddern Regarding bumblebee, I noticed https://github.com/ori-mrg/robotcar-dataset-sdk/tree/master/models only has Pinhole intrinsic calibration for stereo_narrow_left. stereo_narrow_right, stereo_wide_left, stereo_wide_right.
However, the camera images are stored as stereo/left stereo/right and stereo/centre. 

What about the intrinsics of stereo/centre? Also, which ones of the two stereo_narrow_*.txt or stereo_wide_*.txt are valid for stereo/left and stereo/right images?

**Comment by jarvisyjw** [comment]
![Image](https://github.com/user-attachments/assets/41534bf2-80ad-4759-b13d-0555edc16029)
You can refer to this part of camera_model.py provided by the SDK.
