### ISSUE TITLE
About the extrinsic parameters

### ISSUE THREAD

**Issue by nkwangyh** [oxford-ori/robotcar-dataset-sdk#9]
I'm currently working on multiple camera coperation in the SLAM systems and I'm really interested in your dataset. But I'm a little confused on the extrinsic parameters in the provided SDK. I don't know the exact meaning of the parameters and I don't find any description either.
According to "SE3MatrixFromComponents.m", the parameters should be a translation vector followed by three Euler angles. And according to the parameters you provided, I guess all the transformation matrices from extrinsic parameters after processing with "SE3MatrixFromComponents.m" should be the transformations from the sensors to the stereo camera which is facing x direction. And the equations should be right:

Trans_4by4 = SE3MatrixFromComponents(sensor_parameters_1by6)
Corresponding_Point_in_stereo_frame = Trans_4by4 * Point_in_sensor_frame

So am I right or not? Could you help me?

And anther question is about the extrinsic parameter calibration of the cameras. Could you share me some experience about the extrinsic parameter calibration of the cameras since your paper doesn't talk much about that? And could you tell me the accuracy of the camera extrinsic calibraions? What's more, are there some camera extrinsic calibration sequences in the dataset? Thank you very much!

**Comment by wmaddern** [comment]
That is correct - note we use the JPL convention for sensor coordinate frames (x-forward, y-right, z-down) and ZYX order Euler angles (roll, pitch, yaw). The function you mention converts these parameters to a 4x4 homogenous transform matrix.

The extrinsic calibration process is described in Section A. 2) in the paper. Since the data was collected over such a long period we cannot guarantee that the provided calibration parameters will be accurate for a specific use case for every dataset, hence we suggest using online calibration approaches (e.g. local SFM) if you want the best accuracy for your application.
